//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ngx.Common.MetaDataExtraction.DatabaseExtractors.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataStructure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStructure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ngx.Common.MetaDataExtraction.DatabaseExtractors.Resources.DataStructure", typeof(DataStructure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowNulls.
        /// </summary>
        internal static string AllowNulls {
            get {
                return ResourceManager.GetString("AllowNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildField.
        /// </summary>
        internal static string ChildField {
            get {
                return ResourceManager.GetString("ChildField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildTable.
        /// </summary>
        internal static string ChildTable {
            get {
                return ResourceManager.GetString("ChildTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string CloseTag {
            get {
                return ResourceManager.GetString("CloseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataStructure.
        /// </summary>
        internal static string DataStructureName {
            get {
                return ResourceManager.GetString("DataStructureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataStructures.
        /// </summary>
        internal static string DataStructures {
            get {
                return ResourceManager.GetString("DataStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyNode.
        /// </summary>
        internal static string EmptyNode {
            get {
                return ResourceManager.GetString("EmptyNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendedProperties.
        /// </summary>
        internal static string ExtendedProperties {
            get {
                return ResourceManager.GetString("ExtendedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendedProperty.
        /// </summary>
        internal static string ExtendedProperty {
            get {
                return ResourceManager.GetString("ExtendedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoNumber.
        /// </summary>
        internal static string IsAutoNumber {
            get {
                return ResourceManager.GetString("IsAutoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainMenu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLength.
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuAllow.
        /// </summary>
        internal static string MenuAllow {
            get {
                return ResourceManager.GetString("MenuAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaDataRoot.
        /// </summary>
        internal static string MetaDataRoot {
            get {
                return ResourceManager.GetString("MetaDataRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodName.
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetType.
        /// </summary>
        internal static string NetType {
            get {
                return ResourceManager.GetString("NetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string OpenTag {
            get {
                return ResourceManager.GetString("OpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/.
        /// </summary>
        internal static string OpenTagClose {
            get {
                return ResourceManager.GetString("OpenTagClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal.
        /// </summary>
        internal static string Ordinal {
            get {
                return ResourceManager.GetString("Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OriginalName.
        /// </summary>
        internal static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherStructures.
        /// </summary>
        internal static string OtherStructures {
            get {
                return ResourceManager.GetString("OtherStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentKeyField.
        /// </summary>
        internal static string ParentKeyField {
            get {
                return ResourceManager.GetString("ParentKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentRelation.
        /// </summary>
        internal static string ParentRelation {
            get {
                return ResourceManager.GetString("ParentRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentRelations.
        /// </summary>
        internal static string ParentRelations {
            get {
                return ResourceManager.GetString("ParentRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentTable.
        /// </summary>
        internal static string ParentTable {
            get {
                return ResourceManager.GetString("ParentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKField.
        /// </summary>
        internal static string PKField {
            get {
                return ResourceManager.GetString("PKField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluralName.
        /// </summary>
        internal static string PluralName {
            get {
                return ResourceManager.GetString("PluralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey.
        /// </summary>
        internal static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        internal static string RegEx {
            get {
                return ResourceManager.GetString("RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingularName.
        /// </summary>
        internal static string SingularName {
            get {
                return ResourceManager.GetString("SingularName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=##DS##;Integrated Security=SSPI;initial catalog=##IC##.
        /// </summary>
        internal static string SQLConn {
            get {
                return ResourceManager.GetString("SQLConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=##DS##;initial catalog=##IC##;user id=##UID##;password=##PASS##.
        /// </summary>
        internal static string SQLPassConn {
            get {
                return ResourceManager.GetString("SQLPassConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLType.
        /// </summary>
        internal static string SQLType {
            get {
                return ResourceManager.GetString("SQLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoredProcedures.
        /// </summary>
        internal static string StoredProcedures {
            get {
                return ResourceManager.GetString("StoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableConstraints.
        /// </summary>
        internal static string TableConstraints {
            get {
                return ResourceManager.GetString("TableConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableRelations.
        /// </summary>
        internal static string TableRelations {
            get {
                return ResourceManager.GetString("TableRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Table.
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeName.
        /// </summary>
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIStructure.
        /// </summary>
        internal static string UIStructure {
            get {
                return ResourceManager.GetString("UIStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIStructures.
        /// </summary>
        internal static string UIStructures {
            get {
                return ResourceManager.GetString("UIStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefinedTypes.
        /// </summary>
        internal static string UserDefinedTypes {
            get {
                return ResourceManager.GetString("UserDefinedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebApplication.
        /// </summary>
        internal static string WebApplication {
            get {
                return ResourceManager.GetString("WebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinApplication.
        /// </summary>
        internal static string WinApplication {
            get {
                return ResourceManager.GetString("WinApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;.
        /// </summary>
        internal static string XMLVersion {
            get {
                return ResourceManager.GetString("XMLVersion", resourceCulture);
            }
        }
    }
}
